### ISSUE TITLE
Tesselation error

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#113]
Can be reproduced when changing the membership level threshold fast.

```
java.lang.ArrayIndexOutOfBoundsException: 105
    at jogamp.opengl.glu.tessellator.PriorityQSort.pqInit(PriorityQSort.java:149)
    at jogamp.opengl.glu.tessellator.Sweep.InitPriorityQ(Sweep.java:1245)
    at jogamp.opengl.glu.tessellator.Sweep.__gl_computeInterior(Sweep.java:1312)
    at jogamp.opengl.glu.tessellator.GLUtessellatorImpl.gluTessEndPolygon(GLUtessellatorImpl.java:525)
    at javax.media.opengl.glu.GLU.gluTessEndPolygon(GLU.java:898)
    at org.caleydo.core.view.opengl.util.spline.TesselationRenderer.render3(TesselationRenderer.java:218)
    at org.caleydo.core.view.opengl.util.spline.Band.fill(Band.java:176)
    at org.caleydo.core.view.opengl.layout2.GLGraphics.fillPolygon(GLGraphics.java:422)
    at org.caleydo.view.bicluster.elem.band.BandElement.renderImpl(BandElement.java:285)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:201)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:295)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:201)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:295)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:201)
    at org.caleydo.core.view.opengl.layout2.GLElementDecorator.renderImpl(GLElementDecorator.java:47)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:201)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.renderImpl(GLElementContainer.java:295)
    at org.caleydo.core.view.opengl.layout2.GLElement.render(GLElement.java:201)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.renderPass(AGLElementView.java:255)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:214)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:588)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:572)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:149)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1034)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:161)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:855)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:572)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Tessellation Error: 100902
```

**Comment by sgratzl** [comment]
as you can see from the stack trace, this is a problem of JOGL. 

I also have this exception regulary, but I have no idea, what the special conditions of the spline are. I don't even know, who is catching this exception
