### ISSUE TITLE
When changing thresholds sometimes the visualization freezes or turns blank

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#27]
This happens in particular when the thresholds are changed fast.

**Comment by mstreit** [comment]
Happens when fish-eye is active and the global thresholds are changed.
Exception:

```
org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:237) 1282 invalid operation: 
javax.media.opengl.GLException: java.lang.ArrayIndexOutOfBoundsException: 54
    at jogamp.opengl.ThreadingImpl.invokeOnWorkerThread(ThreadingImpl.java:224)
    at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:211)
    at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:658)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:375)
    at com.jogamp.opengl.util.DefaultAnimatorImpl.display(DefaultAnimatorImpl.java:50)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:142)
    at com.jogamp.opengl.util.FPSAnimator$1.run(FPSAnimator.java:128)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 54
    at org.caleydo.view.heatmap.v2.spacing.FishEyeSpacingCalculator$DeterminedSpacingImpl.getPosition(FishEyeSpacingCalculator.java:130)
    at org.caleydo.view.heatmap.v2.HeatMapElement.render(HeatMapElement.java:434)
    at org.caleydo.view.heatmap.v2.HeatMapElement.renderPickImpl(HeatMapElement.java:495)
    at org.caleydo.core.view.opengl.layout2.GLElement.renderPick(GLElement.java:253)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.renderPickImpl(AnimatedGLElementContainer.java:472)
```

**Comment by sgratzl** [comment]
theory: 
1. during manipulation of the threshold the indices of the virtual array will be manipulated
2. afterwards a table perspective changed event wil be triggered
3. ONE FRAME LATER the event will be received by the heatmap triggered a relayout
4. However between 2. and 3. there is state / frame where the (updated) table perspective should be rendered but with the old layout, as the event will arrive in a frame later

possible workaround: 
- call heatmap.relayout besides fireTablePerspectiveChanged

**Comment by sgratzl** [comment]
> afterwards a table perspective changed event wil be triggered

it didn't solve the problem, as the problem occured during picking and the order is: 1. picking, 2. layouting, 3. rendering 

-> more defense layouter

but there is still the issue that for one frame between the manipulation of the table perspective and the arrivial of the table perspective changed events the system is in a inconsistent state

**Comment by sgratzl** [comment]
one frame inconsistency is acceptable
